### ISSUE TITLE
Drop /etc/profile.d/256term.* files completely

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#107]
After talking to @keszybz, we have come to a conclusion to drop these shell scripts completely. There are used to set `$TERM` shell variable by doing there own heuristic, but most of the terminal emulators these days should set the `$TERM` variable by themselves.

For more info, please see https://fedoraproject.org/wiki/Changes/Drop_256term.sh.

**Comment by covex** [comment]
So now after a years from
https://fedoraproject.org/wiki/Features/256_Color_Terminals
to
https://fedoraproject.org/wiki/Changes/Drop_256term.sh

I have again the TERM variable in xterm set to "xterm" instead "xterm-256color" and the thing displays again like 5 years before. 
Should we do this again?
https://xaizek.github.io/2013-04-14/howto-set-xterm-256color-term-in-slackware/

**Comment by keszybz** [comment]
Please read the change page. It explains that having the terminal emulator set the TERM variable to a wrong value and then having shell scripts implemented separately for every shell detect this and correct it just doesn't make sense. Please have your terminal emulator set $TERM based on what it supports. If xterm sets it wrong, open a bug https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=xterm.

**Comment by covex** [comment]
TERM="xterm" is perfectly OK, just it returns us 5 years back. xterm in Fedora is not using "xterm-256colors" by default. Should it be considered bug?

**Comment by keszybz** [comment]
Yes.

**Comment by covex** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1577159
