### ISSUE TITLE
ifdown-post removes user's ppp configuration

### ISSUE THREAD

**Issue by iavael** [fedora-sysv/initscripts#155]
/etc/sysconfig/network-scripts/ifdown-post started to delete user's files in /etc/ppp/peers/ after 5d6156454bf8f6dab4a5fdd7e1bf6cdc72c09456

ifdown-post executes from /etc/ppp/ip-down every time ppp used, so it deletes files in /etc/ppp/peers every time when ppp shuts down even if it wasnt's spawnd from network-scripts.

**Comment by deekej** [comment]
Hello. Thanks for the report.

But almost all code related to PPP was moved to a different package `ppp` (in Fedora). My guess is that some parts of the PPP code uses the `ifdown-post` in a (hackish?) way that causes your issue.

The source code for the PPP package in Fedora is here:
https://src.fedoraproject.org/rpms/ppp/tree/master

I might look into this at some point, but currently I'm busy working on something different. Feel free to look into the PPP source code yourself, if you feel up to it. ;)

**Comment by deekej** [comment]
OK, so the problem was caused by this change:
https://github.com/fedora-sysv/initscripts/commit/5d6156454bf8f6dab4a5fdd7e1bf6cdc72c09456?diff=unified#diff-44e38bbe9c5d9fdcb1db9d0e7cd266f3L21

There's a logical mistake. I will fixit ASAP.
