### ISSUE TITLE
Move sysconfig/netconsole to a different package

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#186]
Same reason as with #185.

The question is - where the `netconsole` file should live? network-scripts? Network Manager? setup package?

**Comment by lnykryn** [comment]
In ideal case, this should be provided by kernel package since it depends on a kernel module.

**Comment by deekej** [comment]
Good point. Lets hope kernel guys would be okay with this... :)

**Comment by deekej** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1577944

**Comment by deekej** [comment]
Resolved with #207.
