### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [fedora-sysv/initscripts#298]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by jamacku** [comment]
Hi, Is there any documentation or guide describing process of how to migrate project to Weblate? Thank you.

**Comment by jamacku** [comment]
> Hello, the Fedora project migrates its translation platform to Weblate [1].
> 
> This tool directly interact with your git repository, and requires us to know:
> 
>     * [mandatory] which branch is your development branch?
master

>     * [mandatory] have you merged latest translation from Zanata and locked the project?
no, I'm not maintainer in Zanata

>     * [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
> 
>     * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
> 
>     * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
> 
>     * [optional] do you need us to activate any specific checks? (this is a setting per component [3])
> 
>     * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)
> 
> 
> Please note:
> 
>     * For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
> 
>     * In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
> 
>     * You can change your mind over time, just reach [trans@lists.fedoraproject.org](mailto:trans@lists.fedoraproject.org)
> 
> 
> [1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/
> [2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
> [3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
Le 2020-01-24 15:06, Jan Macku a écrit :
> Hi, Is there any documentation or guide describing process of how to
> migrate project to Weblate? Thank you.

Hi Jan,

thanks for your answers.

To migrate to Weblate:

* Pull Zanata translations and commit it in your repository (no need to 
be admin)
** In parallel, reach the maintainers to lock the project 
https://fedora.zanata.org/project/view/initscripts/people
* Delete po files with no translations (you may use pocount from 
language toolkit)
* Connect once to https://translate.fedoraproject.org with your account 
(so I see you in user list)

 From there, I'll create the Weblate configuration in 
https://translate.fedoraproject.org/ and make you admin.
And this will be all for Weblate.

What surprise me with your project is that all translation files are 2 
years old. Is it normal? A lot of releases happened since last update.

**Comment by jamacku** [comment]
>     To migrate to Weblate:
>     
>     * Pull Zanata translations and commit it in your repository (no need to
>     be admin)
>     * Delete po files with no translations (you may use pocount from
>     language toolkit)
Done in PR: #303

**Comment by Jibec** [comment]
To help you, the Zanata admin locked your project.

**Comment by jamacku** [comment]
Thank you for your help. There is already PR #305  from Weblate, but Weblate project is locked.

 Is there anything else I should do to complete this process?

**Comment by Jibec** [comment]
I feel like I have everything required now. I'll finish configuration soon.

**Comment by jamacku** [comment]
So I'm closing this issue. Thank you Jean.

**Comment by Jibec** [comment]
Please reopen until it's really done.

**Comment by Jibec** [comment]
configuration is done: https://translate.fedoraproject.org/projects/fedora-sysv/initscripts/

jamacku is admin of the project
Weblate will automatically update po files when you update the pot file in your repository
Weblate will reuse the open pull request and squash git commits per author to limit the number of commits
