### ISSUE TITLE
grep -L return value breaks network start

### ISSUE THREAD

**Issue by dirteat** [fedora-sysv/initscripts#300]
Spotted by M. W. on Mageia:

* Noteworthy changes in release 3.2 (2018-12-20) [stable]
** Changes in behavior
  The --files-without-match (-L) option now causes grep to succeed
  when a file is listed, instead of when a line is selected.  This
  resembles what git-grep does.

This breaks the init.d/network scripts there:

`if LANG=C grep -EL "^ONBOOT=['\"]?[Nn][Oo]['\"]?" ifcfg-$i > /dev/null ;`
`then`
`     # this loads the module, to preserve ordering`
`          is_available $i`
`          continue`
`fi`

and just after for the `# Bring up xDSL and VPN interfaces`.

The fix is to either use a negation, or the negated option `-l`

Cheers,
Chris.

**Comment by lnykryn** [comment]
I would suggest replacing this with something like
if ( . ./ifcfg-$i ; is_false $ONBOOT ;  ) ; then ....
Using standard is_true/is_false function but sourcing the ifcfg file in the subshell, so we don't mess up the current environment.

**Comment by jamacku** [comment]
Hi,
Pull request #301 should fix your issue. In case It won't, please let me know.

**Comment by jamacku** [comment]
Fixed in initscripts 10.03
