### ISSUE TITLE
initscripts.spec: network-scripts package should Require: ethtool

### ISSUE THREAD

**Issue by ovitters** [fedora-sysv/initscripts#337]
`network-scripts/ifup-eth` calls the function `ethtool_set` various times, see e.g.:
https://github.com/fedora-sysv/initscripts/blob/fc6164b75090f03eed7504195d1fa9f0915ea862/network-scripts/ifup-eth#L144-L149

this `ethtool_set` function is defined in `network-scripts/network-functions`, see 

https://github.com/fedora-sysv/initscripts/blob/fc6164b75090f03eed7504195d1fa9f0915ea862/network-scripts/network-functions#L198-L217

However, initscripts.spec does not have a require for ethtool. I think it should be added in the network-scripts package.

Current Requires are:

https://github.com/fedora-sysv/initscripts/blob/fc6164b75090f03eed7504195d1fa9f0915ea862/initscripts.spec#L97-L108

I do see in the history that various changes were made to reduce the ethtool dependency/usage.

**Comment by jamacku** [comment]
Thank you for reporting this issue.

**Comment by jamacku** [comment]
Fixed
