### ISSUE TITLE
Document everything that could appear in ifcfg files.

### ISSUE THREAD

**Issue by lnykryn** [fedora-sysv/initscripts#36]
Most of those options are documented in sysconfig.txt, but the documented in terribly outdated. We should create a manpage for that.

**Comment by deekej** [comment]
Self-NOTE: Probably the best course of action would be use markdown, and some markdown->>manpage converter.

**Comment by Conan-Kudo** [comment]
This is something that @pavlix is interested in as part of potentially revamping and unifying `ifcfg` support in NetworkManager.

openSUSE's wicked project contains [extensive man pages on the SUSE ifcfg format](https://github.com/openSUSE/wicked/tree/master/man), though I'm not fully certain of the differences between the Red Hat/Fedora/Mageia and the SUSE flavors of ifcfg.

**Comment by Conan-Kudo** [comment]
I've also got wicked packaged for Fedora in a COPR: https://copr.fedorainfracloud.org/coprs/ngompa/Wicked/

So if you want to, you can install `wicked` and take a look at it.

**Comment by deekej** [comment]
Thanks @Conan-Kudo, I'll look at it once I get to this issue... :)

**Comment by Conan-Kudo** [comment]
@deekej It might also be worth talking to @mtomaschewski, who has been the poor soul maintaining the ifcfg stuff for SUSE in both [wicked](https://github.com/openSUSE/wicked) and [sysconfig](https://github.com/openSUSE/sysconfig).

Maybe there's something that could be done to make things better for both!

(I could only hope and dream...)

**Comment by lnykryn** [comment]
fedora and rhel are not using ifcfgs by defualt anymore. Let's just close this
