### ISSUE TITLE
killproc() does not execute properly on a busybox-bash environment

### ISSUE THREAD

**Issue by mengtanhzc** [fedora-sysv/initscripts#396]
**initscripts version the issue has been seen with**
1) initscripts 10.06
2) BusyBox v1.32.1

**Steps to reproduce the problem**
```
    #!/bin/bash
    
    . /etc/init.d/functions
    
    test()
    {
            sleep 30 &
            killproc sleep
    }
    
    test
```
run this testcase returns an error, and sleep is not killed.
![image](https://user-images.githubusercontent.com/41482086/138225687-eb9140ee-5949-4a3f-ad4c-5e7539b3b66f.png)

Instead of using bash package on my environment, I am using busybox-bash, but **busybox-bash does not support +=**, thus causing this problem. 
Can I submit a PR to fix this problem?

**Comment by jamacku** [comment]
Feel free to submit a PR I'll be happy to review it.

**Comment by mengtanhzc** [comment]
> Feel free to submit a PR I'll be happy to review it.

Thank you very much! I have just created a PR to solve it, please review~

**Comment by jamacku** [comment]
Thank you for your contribution!
