### ISSUE TITLE
Shellcheck warnings

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#43]
Most of the shellcheck warnings should be fixed (whenever possible) to make checking with shellcheck in the future more convenient. Right now, there are too many warnings, which can obfuscate new (problematic) warnings.

**Comment by lnykryn** [comment]
Also we might try to use Kamil's csdiff (https://github.com/kdudka/csdiff) Shellcheck can give you output in gcc-like format, so you could run test for the current head and then for the pull request and create a diff between those.

**Comment by jamacku** [comment]
There is CI job currently available in master branch, which uses shellcheck and csdiff. See above.
