### ISSUE TITLE
Logic error when there is no /run

### ISSUE THREAD

**Issue by superteacherdu** [fedora-sysv/initscripts#436]
/etc/rc.d/init.d/functions  line: 186
"local pid_file=${2:-/run/$base.pid}" , if my linux has no /run, but /var/run, there is a error, I have no /run/sshd.pid. Such as my directory is /var/run, but I not want the /run

**Comment by lnykryn** [comment]
You should report this as a bug for your distribution. Based on FHS 3.0 /run is now a standard directory, and /var/run should be a symlink to it for backwards compatibility. https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html
