### ISSUE TITLE
remove unnecessary dependencies?

### ISSUE THREAD

**Issue by f1-outsourcing** [fedora-sysv/initscripts#447]
I used to have only installed network-scripts 10.10 without dependencies, I do not really get why I have to install now 2 extra rpms.

```
Upgrading:
 initscripts                                 x86_64                   10.17-1.el9                     
 network-scripts                             x86_64                   10.17-1.el9         
Installing dependencies:
 dbus-tools                                  x86_64                   1:1.12.20-7.el9       
 initscripts-rename-device                   x86_64                   10.11.5-1.el9          
```

**Comment by lnykryn** [comment]
initscripts-rename-device was split from the network-scripts and we need dbus to talk to NetworkManager

**Comment by f1-outsourcing** [comment]
NetworkManager is not installed, so how can you need to talk to it? Why do you need it now and not before?

**Comment by jamacku** [comment]
- https://github.com/fedora-sysv/initscripts/pull/425
