### ISSUE TITLE
Code optimization in etc/rc.d/init.d/functions

### ISSUE THREAD

**Issue by linzhuorong** [fedora-sysv/initscripts#459]
Check whether the /var/run/XXX.pid file can be added to __pids_var_run() in etc/rc.d/init.d/functions.
![image](https://github.com/fedora-sysv/initscripts/assets/104970073/9ef01240-86a2-4a07-ab5d-ae76bb172f23)

**Comment by lnykryn** [comment]
On all modern Linux distributions /var/run is just a symlink to /run.
