### ISSUE TITLE
Bug in is_nm_handling()

### ISSUE THREAD

**Issue by RN97** [fedora-sysv/initscripts#487]
Hey, 

I recently found a bug in the is_nm_handling() function in the grep statement. 

```
is_nm_handling ()
 {
      LANG=C nmcli -t --fields device,state dev status 2>/dev/null | grep -q "^\(${1}:connected\)\|\(${1}:connecting.*\)$"
 }
```

From the above, you will notice that the "^" anchor is applied to the "connected" case and does not apply to the "connecting" case in the grep due to the way the brackets () are placed. This can cause the grep statement to incorrectly return a match.

For ex: When trying to check for eth0 using is_nm_handling(), "bondeth0:connecting" would also match the grep and return incorrectly.

```
rn97@mac:~$ echo bondeth0:connecting | grep "^\(eth0:connected\)\|\(eth0:connecting.*\)$"
bondeth0:connecting
rn97@mac:~$
```

Here is my proposed fix for this issue. 
```
is_nm_handling ()
 {
-    LANG=C nmcli -t --fields device,state dev status 2>/dev/null | grep -q "^\(${1}:connected\)\|\(${1}:connecting.*\)$"
+    LANG=C nmcli -t --fields device,state dev status 2>/dev/null | grep -q "^\(${1}:connected\|${1}:connecting.*\)$"
 }

```

Thanks

**Comment by lnykryn** [comment]
Yeah, the current regexp does not look correct. Can you submit the change as a pull request?

**Comment by RN97** [comment]
Created a pull request for the above issue.

https://github.com/fedora-sysv/initscripts/pull/488
