### ISSUE TITLE
Add a retry in ifup-eth for arping sendto failure

### ISSUE THREAD

**Issue by xanoxes** [fedora-sysv/initscripts#489]
We noticed that in bond mode=4, sendto() in arping may failed cause of the negotiation of bond4 is not complete. Thus the usable_slaves is 0, and sendto will return failure in kernel. In this way, arping will return -1 cause of the number of send is same as number of recv (both 0). The shell code now in ifup-eth will consider this situation as an IP address conflict, although it will be all fine after the negotiation of bond4. This can cause unexpected loss of ip addresses. 
We make a change in ifup-eth to identify whether an IP address conflict occurs.
[retry-arping-when-bring-up-bond4.patch](https://github.com/user-attachments/files/17107632/retry-arping-when-bring-up-bond4.patch)

**Comment by xanoxes** [comment]
---
 network-scripts/ifup-eth | 14 +++++++++++---
 1 file changed, 11 insertions(+), 3 deletions(-)
 
diff --git a/network-scripts/ifup-eth b/network-scripts/ifup-eth
index 0e97d2c..a5475e7 100755
--- a/network-scripts/ifup-eth
+++ b/network-scripts/ifup-eth
@@ -295,9 +295,17 @@ else
                 if [ "${REALDEVICE}" != "lo" ] && ! is_false "${arpcheck[$idx]}"; then
                     ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
                     if [ $? = 1 ]; then
-                        ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
-                        net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}."
-                        exit 1
+                        if [ "{$ARPINGMAC}" ]; then
+                            net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}."
+                            exit 1
+                        else
+                            ARPING1=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
+                            if [ $? = 1 ]; then
+                                ARPINGMAC1=$(echo $ARPING1 |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
+                                net_log $"Error, some other hosts ($ARPINGMAC1) already uses address ${ipaddr[$idx]}."
+                                exit 1
+                            fi
+                        fi
                     fi
                 fi
 
-- 
2.33.0

**Comment by xanoxes** [comment]
[retry-arping-when-bring-up-bond4.patch](https://github.com/user-attachments/files/17107631/retry-arping-when-bring-up-bond4.patch)

**Comment by lnykryn** [comment]
That patch does not look correct, I don't see what would set ARPINGMAC in the if statement.

Also please submit any patches as pull requests, it is easier to do a review that way.

**Comment by xanoxes** [comment]
> That patch does not look correct, I don't see what would set ARPINGMAC in the if statement.
> 
> Also please submit any patches as pull requests, it is easier to do a review that way.

Y're right, ARPINGMAC is null now the first time. I am going to submit a pull request. We dont use ARPING_WAIT cause of it will slow the start time of nic. On a physical machine with multiple NICs, ARPING_WAIT will make the network inits very long. So we just give it a retry only when ARPINGMAC is null.
