### ISSUE TITLE
Outdated translations

### ISSUE THREAD

**Issue by piotrdrag** [fedora-sysv/initscripts#59]
Translations haven’t been updated in 4 years. It would be great if you could regularly push/pull translations to/from <https://fedora.zanata.org/project/view/initscripts>.

**Comment by lnykryn** [comment]
Hmm, it looks that zanata does not like our pot file (at least because of encoding). If anyone wants to work on that, I would be more then happy to merge pull requests and give them access to zanata.

**Comment by deekej** [comment]
This has been resolved by commit in #61.
