### ISSUE TITLE
Drop 'usleep' from initscripts completely in F28.

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#68]
There's no longer need to have this utility as part of the initscripts package. The more suitable package would be the *coreutils* package.

NOTE: This utility can't be just replaced by 'sleep' utility, because it has different behaviour and cmdline options.

**Comment by kdudka** [comment]
We have decided to keep this in initscripts until the utility is deprecated.

**Comment by deekej** [comment]
We will try to get a patch to coreutils for the sleep utility first. If that does not work out, then we will move this utility to util-linux. In either case, we have decided to keep this utility around.

**Comment by deekej** [comment]
Sorry, I forgot to mention we want to get this into coreutils upstream.

We were thinking of symlink/hardlink approach, where the sleep binary would check the argv[0] when it starts. If the name in argv[0] would be 'usleep', then it would divide the sleep value correspondingly, and proceed as usual.

**Comment by kdudka** [comment]
Unlikely.  This is what coreutils upstream replied in 2015: https://bugzilla.redhat.com/1189877#c1

**Comment by deekej** [comment]
Well, I'm willing to try that again. :)
