### ISSUE TITLE
Create the CHANGELOG files

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#71]
We should start using some sort of CHANGELOG file so it's easier to track changes to behaviour. I guess it would be wise to use 2 changelog files - one for network scripts, and one for the rest.

**Comment by lnykryn** [comment]
Meh, in the past we have generated changelog from the git log. But since the code is easily accessible on github and we don't have ten new shiny features every release, I don't think it is worthy.

**Comment by deekej** [comment]
Well, we usually generate some documentation for the BZs fixed anyway, so we might as well put those changes into changelog. And since we don't have many shiny features every release I think it should be feasible.

**Comment by deekej** [comment]
Meh, lets just use the git log when needed. We are dropping the ChangeLog completely anyway...
