### ISSUE TITLE
Move 'initscripts.tmpfile.d' into different package (or remove it)

### ISSUE THREAD

**Issue by deekej** [fedora-sysv/initscripts#73]
We should consider moving this into different package, like *setup*. Alternatively, since we're maintaining the *.spec file and the 'initscripts.tmpfile.d' now contains only one instructions to create `/var/run/netreport/` folder, we could just add it into specfile installation phase. @lnykryn, what do you think?

**Comment by lnykryn** [comment]
This is tmpfiles snipet for netreport. It should stay.
